### ISSUE TITLE
feature request: Ignore files or files types

### ISSUE THREAD

**Issue by programminglaboratorys** [dvillaseca/cloudscript-server#1]
is there any chance to add support to ignore files? I have some files and don't want to publish them with cloudscript, I wish instead of moving them to just ignore them. make the project load .gitignore and based on that ignore files that could be useless or have sensitive information

**Comment by dvillaseca** [comment]
> is there any chance to add support to ignore files? I have some files and don't want to publish them with cloudscript, I wish instead of moving them to just ignore them. make the project load .gitignore and based on that ignore files that could be useless or have sensitive information

The system currently only uses .js files in the root folder

I think having an ignore system could be useful but I think using the .gitignore can cause issues in some projects
Would it work for you to have a custom ignore file for this?
ie: .cloudscriptignore

**Comment by dvillaseca** [comment]
feature added in version 1.1.5
